export type ISheetsData = {
  [key: string]: string[][];
  Mayoristanet: string[][];
  'Kalis.': string[][];
  Victory: string[][];
  'Tecnigraf.': string[][];
  'Todo envase': string[][];
  LDT: string[][];
  Dankon: string[][];
  'Carlos Lento': string[][];
  LYL: string[][];
  Eridanus: string[][];
  Blancaluna: string[][];
  Gasatex: string[][];
  Nogada: string[][];
  Marino: string[][];
  AADI: string[][];
  Prohygene: string[][];
  Henning: string[][];
  'Campo austral.': string[][];
};
