export type ISheetsData = {
  [key: string]: Map<string, string[]>;
  Mayoristanet: Map<string, string[]>;
  'Kalis.': Map<string, string[]>;
  Victory: Map<string, string[]>;
  'Tecnigraf.': Map<string, string[]>;
  'Todo envase': Map<string, string[]>;
  LDT: Map<string, string[]>;
  Dankon: Map<string, string[]>;
  'Carlos Lento': Map<string, string[]>;
  LYL: Map<string, string[]>;
  Eridanus: Map<string, string[]>;
  Blancaluna: Map<string, string[]>;
  Gasatex: Map<string, string[]>;
  Nogada: Map<string, string[]>;
  Marino: Map<string, string[]>;
  AADI: Map<string, string[]>;
  Prohygene: Map<string, string[]>;
  Henning: Map<string, string[]>;
  'Campo austral.': Map<string, string[]>;
};
